### ISSUE TITLE
lets go/home page - error of interpretation - section 01

### ISSUE THREAD

**Issue by haileypopma** [GrantMatejka/CSC-308-Travel#4]
make the buttons at the bottom of the screen bigger so they fill the entire bottom instead of being little squares - will make them easier to push on 
<img width="283" alt="Screen Shot 2020-02-05 at 11 41 59 AM" src="https://user-images.githubusercontent.com/60552863/73876832-89631180-480c-11ea-861d-b758b9b9b15a.png">

**Comment by GrantMatejka** [comment]
The prototype was intended to show the general layout and intention of the app, much more testing and development will go into seeing what exactly is needed out of the lower navigation bar and what functionality is needed from it. 

Due to this, the button size, shape and appearance will change throughout the development of the app.
